### ISSUE TITLE
Support uploading and serving more common file content types.

### ISSUE THREAD

**Issue by shurcooL** [pavben/InstantShare#17]
For example, uploading a .html file should serve it as `text/html` content type (rather than `application/octet-stream` as it is now).

See https://godoc.org/mime for how this can be done automatically for many common types.

**Comment by pavben** [comment]
Some file types we may want to keep as application/octet-stream even if there is a "proper" mime type. I may want you to download the .html file as is instead of it displaying as a webpage. I suppose you could still right click and "Save As..." as we do with images. Yeah ok. As long as it's still possible to download it verbatim without any form of pain, I'm good with this.

**Comment by shurcooL** [comment]
Absolutely, it should still be possible to explicitly download through the usual "Save as..." mechanism. That is a requirement I do not want to break.

But this will allow one to preview common types that browsers display well without being forced to download. So it's an additive enhancement.

**Comment by shurcooL** [comment]
Also, we should set the `Content-Disposition` header to something that we want. Details are [here](https://stackoverflow.com/questions/20508788/do-i-need-content-type-application-octet-stream-for-file-download/20509354#20509354).
